name: Daily database export
run-name: ${{ github.actor }} is exporting the database and releasing it

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  export:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v6

      - name: 📆 Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: 📦 Download export from server
        run: |
          curl -L -o el-guacal-db-${{ steps.date.outputs.date }}.zip https://server.elguacal.com/api/export/zip

      - name: 🚀 Release
        run: |
          gh release create "data-export@${{ steps.date.outputs.date }}" \
            --title "data-export@${{ steps.date.outputs.date }}" \
            --notes "Daily automated data export of El Guacal database." \
            el-guacal-db-${{ steps.date.outputs.date }}.zip
