name: server tests
run-name: ${{ github.actor }} is running tests

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - server/**
      - .github/workflows/server-tests.yml

jobs:
  # Label of the container job
  tests:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: node:lts-hydrogen

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgis/postgis:15-3.3
        ports:
          - 5432/tcp
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: pataruco
          POSTGRES_USER: pataruco
          POSTGRES_DB: productsdb
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v3

      # Performs a clean installation of all dependencies in the `package.json` file
      # For more information, see https://docs.npmjs.com/cli/ci.html
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        working-directory: .
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install
        working-directory: .

      - name: run migrations
        run: pnpm migrate
        working-directory: packages/server
        env:
          # The hostname used to communicate with the PostgreSQL service container
          POSTGRES_HOST: postgres
          # The default PostgreSQL port
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
          POSTGRES_PASSWORD: pataruco
          POSTGRES_USER: pataruco
          POSTGRES_DB: productsdb

      - name: run end to end tests
        run: pnpm test:ci
        working-directory: packages/server
        env:
          # The hostname used to communicate with the PostgreSQL service container
          POSTGRES_HOST: postgres
          # The default PostgreSQL port
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
          POSTGRES_PASSWORD: pataruco
          POSTGRES_USER: pataruco
          POSTGRES_DB: productsdb
