name: server-ts checks
run-name: ${{ github.actor }} is linting and runnings tests for server-ts
on:
  pull_request:
    branches:
      - 'main'
    paths:
      - server-ts/**
      - .github/workflows/server-ts-checks.yaml
jobs:
  lint-test:
    name: Lint and tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/hydrogen

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        working-directory: server-ts
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install
        working-directory: server-ts

      - name: check GraphQL schema
        working-directory: server-ts
        run: |
          pnpm codegen
          git diff --exit-code
          exit $?

      - name: run format
        working-directory: server-ts
        run: pnpm format

      - name: run linter
        working-directory: server-ts
        run: pnpm lint
